apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
    traefik.enable: "true"
    traefik.http.routers.api.entrypoints: web
    traefik.http.routers.api.rule: Host(``)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        traefik.enable: "true"
        traefik.http.routers.api.entrypoints: web
        traefik.http.routers.api.rule: Host(``)
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: APACHE_DOCUMENT_ROOT
              value: public/
            - name: APP_ENV
              value: dev
            - name: APP_SECRET
              value: 8d2a5c935d8ef1c0e2b751147382bc75
            - name: PHP_EXTENSION_GD
              value: "1"
            - name: PHP_EXTENSION_INTL
              value: "1"
            - name: PHP_EXTENSION_WEAKREF
              value: "1"
            - name: PHP_EXTENSION_XDEBUG
              value: "1"
            - name: PHP_INI_POST_MAX_SIZE
              value: 50M
            - name: PHP_INI_UPLOAD_MAX_FILESIZE
              value: 50M
            - name: PHP_INI_XDEBUG__REMOTE_AUTOSTART
              value: "1"
            - name: PHP_INI_XDEBUG__REMOTE_CONNECT_BACK
              value: "1"
          image: thecodingmachine/php:8.0-v4-apache-node14
          name: app
          resources: {}
      restartPolicy: Always
      volumes:
        - name: app-claim0
          hostPath:
            path: /var/www/html
status: {}
